[tool.poetry]
name = "alpha"
version = "0.1.0"
description = "This is project alpha"
authors = ["Ketan <ketansahils@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
